### ISSUE TITLE
Replace Slack with Discord

### ISSUE THREAD

**Issue by ntdkhiem** [fuseumass/dashboard#315]
Current implementation for communication is Slack. HUM XI has decided to switch to Discord so we should replace the Slack Channels with Discord Channels.

## Tasks

- [x] Await for HUM to create Discord server
- [x] Disable Slack
- [ ] Add a Discord on top of Slack.
- [ ] Should we remove Slack completely from the dashboard?

## Screenshot
<img width="290" alt="image" src="https://github.com/fuseumass/dashboard/assets/25674728/b0c5bd1d-cd1e-43a9-981e-a8d6dafb2006">

**Comment by ntdkhiem** [comment]
#333
